# Generated by Django 5.1.1 on 2024-10-04 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_taluka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('taluka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='group.taluka')),
            ],
        ),
    ]
