# Generated by Django 5.1.1 on 2024-10-04 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='group.village'),
        ),
    ]
