# Generated by Django 5.1.1 on 2024-10-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_group_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='leader_images'),
        ),
    ]
