# Generated by Django 5.1.1 on 2024-10-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_group_video_status_alter_group_video_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
