# Generated by Django 5.1.1 on 2024-10-13 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_leader_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='group.group')),
            ],
        ),
    ]
