# Generated by Django 5.1.1 on 2024-10-04 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0004_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='group.village')),
            ],
        ),
    ]
