# Generated by Django 5.1.1 on 2024-10-04 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_group_village'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Select_user_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='group.group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
        ),
    ]
