# Generated by Django 5.1.1 on 2024-10-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_message',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='chat_images'),
        ),
    ]
