# Generated by Django 5.1.1 on 2024-10-06 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_chat_message_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='chat_images')),
            ],
        ),
        migrations.AlterField(
            model_name='chat_message',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.chat_images'),
        ),
    ]
