# Generated by Django 5.1.1 on 2024-10-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_chat_images_alter_chat_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_message',
            name='image',
        ),
    ]
