# Generated by Django 5.1.1 on 2024-10-06 13:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_chat_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_message',
            name='msg',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
