# Generated by Django 5.1.1 on 2024-10-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_chat_message_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_images',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
