# Generated by Django 5.1.1 on 2024-10-08 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_leader_pin'),
        ('user', '0011_chat_message_post_typing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_message',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.leader'),
        ),
        migrations.AlterField(
            model_name='chat_message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
