# Generated by Django 5.1.1 on 2024-10-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_chat_message_leader_alter_chat_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_message',
            name='advertise',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
