# Generated by Django 5.1.1 on 2024-10-08 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_leader_pin'),
        ('user', '0013_chat_message_advertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_message',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
    ]
