# Generated by Django 5.1.1 on 2024-10-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_chat_message_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_images',
            name='leader_id',
            field=models.IntegerField(null=True),
        ),
    ]
